name: Autoformat

on:
  issue_comment:
    types: [created, edited]

jobs:
  auto-format:
    # Check if the comment contains the trigger /format-action.
    # Check if the comments come from pull request, exclude those from issue.
    if: |
      contains(github.event.comment.body, '@format-action') &&
      contains(github.event.comment.html_url, '/pull/')
    name: auto-format
    runs-on: ubuntu-latest

    steps:
      - name: resolve pr refs
        id: refs
        uses: eficode/resolve-pr-refs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint with black
        uses: psf/black@stable
        with:
          options: "--verbose"
          src: "."
          jupyter: true
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
