name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          jupyter: true
      - name: Suggest format action on error
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🤖 **Code Formatting Reminder**

            Hello there! 👋 It looks like the code in this pull request might benefit from some formatting improvements ([![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)
            ).
            Fix the issues locally or use our auto format action by commenting `/format` on this PR!
